#https://github.com/RoadkillUK/Motor-on-a-Roller-Blind-for-ESPHOME - Written by RoadkillUK

substitutions:
  devicename: roller_blind
  upper_devicename: Roller Blind
  mystepper: my_stepper # Name of the stepper motor (leave as is)
  speed: 600 steps/s # Set the speed of the motor
  reportin: "0" # Set if you want the blind to report position while moving (causes delay)

  pina: D1 # Swap these \_ coil a
  pinb: D3 # Swap these /
  pinc: D2 # Swap these \_ coil b
  pind: D4 # Swap these /

<<: !include .common_blind.yaml # include the main blind file

# NOTE:  If you find that your shades are going the wrong way, you can change the pin
#        settings or reverse the + and – wires for each of the A and B motor
#        pairs on your driver and the motor will spin in the opposite direction.

# These pinouts are for the original 'Motor on a Roller Blind'